---
apiVersion: v1
kind: Template
metadata:
  name: payload-tracker
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: payload-tracker
  spec:
    optionalDependencies:
    - storage-broker
    - ingress
    testing:
      iqePlugin: payload-tracker
    envName: ${ENV_NAME}
    database:
      name: payloadtracker
    kafkaTopics:
    - replicas: 3
      partitions: 8
      topicName: platform.payload-status
    deployments:
    - name: api
      webServices:
        public:
          enabled: True
      minReplicas: ${{API_REPLICAS}}
      podSpec:
        initContainers:
          - command:
            - ./pt-migration
            image: ${IMAGE}:${IMAGE_TAG}
            inheritEnv: true    
        minReadySeconds: 15
        progressDeadlineSeconds: 600
        image: ${IMAGE}:${IMAGE_TAG}
        command: 
          - ./pt-api
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
        env:
          - name: LOG_LEVEL
            value: ${LOGLEVEL}
          - name: STORAGEBROKERURL
            value: ${STORAGE_BROKER_URL}
    - name: consumer
      minReplicas: ${{CONSUMER_REPLICAS}}
      podSpec:  
        minReadySeconds: 15
        progressDeadlineSeconds: 600
        image: ${IMAGE}:${IMAGE_TAG}
        command: 
          - ./pt-consumer
        resources:
          limits:
            cpu: ${CONSUMER_CPU_LIMIT}
            memory: ${CONSUMER_MEMORY_LIMIT}
          requests:
            cpu: ${CONSUMER_CPU_REQUEST}
            memory: ${CONSUMER_MEMORY_REQUEST}
        env:
          - name: LOG_LEVEL
            value: ${LOGLEVEL}
    jobs:
    - name: vacuum
      schedule: '@daily'
      suspend: ${{CLEANER_SUSPEND}}
      podSpec:
        image: quay.io/cloudservices/payload-tracker-go:${IMAGE_TAG}
        restartPolicy: Never
        command:
          - ./tools/cron-job.sh
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: 200m
            memory: 256Mi


parameters:
- description: Initial amount of memory the payload-tracker container will request.
  displayName: Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 256Mi
- description: Maximum amount of memory for the payload-tracker.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: Initial amount of cpu the payload-tracker will request.
  displayName: CPU Request
  name: CPU_REQUEST
  required: true
  value: 200m
- description: Maximum amount of cpu the payload-tracker can use.
  displayName: CPU Limit
  name: CPU_LIMIT
  required: true
  value: 500m
- description: Initial amount of memory the payload-tracker consumer container will request.
  displayName: Memory Request
  name: CONSUMER_MEMORY_REQUEST
  required: true
  value: 256Mi
- description: Maximum amount of memory for the payload-tracker consumer.
  displayName: Memory Limit
  name: CONSUMER_MEMORY_LIMIT
  required: true
  value: 512Mi
- description: Initial amount of cpu the payload-tracker consumer will request.
  displayName: CPU Request
  name: CONSUMER_CPU_REQUEST
  required: true
  value: 200m
- description: Maximum amount of cpu the payload-tracker consumer can use.
  displayName: CPU Limit
  name: CONSUMER_CPU_LIMIT
  required: true
  value: 500m
- description: The log level to use for logging
  displayName: The log level to use for logging
  name: LOGLEVEL
  required: true
  value: DEBUG
- description: The number of replicas to use for the payload-tracker
  name: API_REPLICAS
  value: '1'
- description: The number of replicas to use for the payload-tracker consumer
  name: CONSUMER_REPLICAS
  value: '3'
- description: Image
  name: IMAGE
  required: true
  value: quay.io/cloudservices/payload-tracker-go
- description: Image tag
  name: IMAGE_TAG
  required: true
- name: ENV_NAME
  value: payload-tracker-api
  required: true
- name: CLEANER_SUSPEND
  value: 'true'
- name: STORAGE_BROKER_URL
  value: "http://storage-broker-processor:8000/archive/url"
