{
 "title": "Payload Tracker",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Service Status Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(payload_tracker_service_status_counter_total[1m])) by (service_name, status, source_name)",
     "legendFormat": "{{service_name}} (source: {{source_name}}) - {{status}}"
    }
   ]
  },
  {
   "title": "Service Status Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(payload_tracker_service_status_counter_total[1m])) by (service_name, status, source_name)",
     "legendFormat": "{{service_name}} (source: {{source_name}}) - {{status}}"
    }
   ]
  },
  {
   "title": "Platform Upload Times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(payload_tracker_upload_time_elapsed_sum[1m]) / rate(payload_tracker_upload_time_elapsed_count[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(payload_tracker_upload_time_by_service_elapsed_sum[1m]) / rate(payload_tracker_upload_time_by_service_elapsed_count[1m])) by (service_name, source_name)",
     "legendFormat": "{{service_name}} (source: {{source_name}})"
    }
   ]
  },
  {
   "title": "Platform Upload Times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(payload_tracker_upload_time_elapsed_sum[1m]) / rate(payload_tracker_upload_time_elapsed_count[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(payload_tracker_upload_time_by_service_elapsed_sum[1m]) / rate(payload_tracker_upload_time_by_service_elapsed_count[1m])) by (service_name, source_name)",
     "legendFormat": "{{service_name}} (source: {{source_name}})"
    }
   ]
  },
  {
   "title": "Payload Tracker API Up",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{service=\"payload-tracker-api\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "platform.payload-status Kafka Messages",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"platform.payload-status\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Topic Lag",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_topic_sum_lag{topic=\"platform.payload-status\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Invalid API Request Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(payload_tracker_api_invalid_request_IDs[$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "platform.payload-status Kafka Messages",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"platform.payload-status\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Topic Lag",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_topic_sum_lag{topic=\"platform.payload-status\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Invalid Consumer Request Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(payload_tracker_consumer_invalid_request_IDs[$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API Responses",
   "type": "graph",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(payload_tracker_responses[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "API Reponse Counts",
   "type": "stat",
   "description": "Uses time range interval to find average",
   "gridPos": { "h": 16, "w": 6, "x": 10, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(payload_tracker_responses[$__interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "API Up (98%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{service=\"payload-tracker-api\"}[24h]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consumer Up (98%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{service=\"payload-tracker-consumer\"}[24h]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"payload-tracker-api\"}[$__range]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Consumer Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"payload-tracker-consumer\"}[$__range]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Consumption Errors (5%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(payload_tracker_consumed_messages[$__range])) / sum(increase(payload_tracker_consume_errors[$__range])) * 100"
    }
   ]
  },
  {
   "title": "Percentage of non-5xx (95%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(payload_tracker_responses{code!~\"5.*\"}[$__interval])) / sum(sum_over_time(payload_tracker_responses[$__interval]))"
    }
   ]
  },
  {
   "title": "Database Query Times",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(payload_tracker_db_seconds_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Message Processing Times",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(payload_tracker_message_process_seconds_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}